---
title: "test_4D_file_read"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# PURPOSE OF PIPELINE: To have/use Chen's raw 4D matrices in Vera
#                      because Seurat in Vera can't read in h5 files
#                      so I'm doing h5 reading in Mac and then exporting
#                      the sparse matrix and its dimnames

```{r pressure, echo=FALSE}
library(Seurat)
library(Matrix)
```

# DO ON MAC
## Write out h5_matrix
```{r include=TRUE}

####################################
# SET THIS 

stage_name <- "iniG1"

####################################

# Directory from where I will access raw matrix.
mac_dir <- "~/Google Drive (ppaul@princeton.edu)/Levine Lab/Orthology Maps/h5_munging/4D_GSE131155_RAW/GSM3764764_"
# Directory where I will place output files.
mac_dir_2 <- "~/Google Drive (ppaul@princeton.edu)/Levine Lab/Orthology Maps/h5_munging/h5_munging_output_files/"

h5_matrix_dir <- paste0(mac_dir, stage_name, "_raw_gene_bc_matrices_h5.h5")

h5_matrix_out_name <- paste0(mac_dir_2, stage_name, "_out.txt")

h5_matrix_rownames_csv <- paste0(mac_dir_2, stage_name, "_rownames.csv")

h5_matrix_colnames_csv <- paste0(mac_dir_2, stage_name, "_colnames.csv")

####################################

### Export h5_matrix + dimnames ### 
h5_matrix <- Read10X_h5(h5_matrix_dir)

writeMM(h5_matrix, h5_matrix_out_name)

write.table(rownames(h5_matrix),
            h5_matrix_rownames_csv,
            row.names = FALSE,
            col.names = FALSE)

write.table(colnames(h5_matrix), 
            h5_matrix_colnames_csv,
            row.names = FALSE,
            col.names = FALSE)
```

# DO ON VERA
## Make h5_matrix_in
```{r include=TRUE}

###################################### 

stage_name <- "iniG1"

#######################################

# same as mac_dir_2 (where the output files are)
vera_dir <- "/home/pprakriti/princeton_google_drive/Levine Lab/Orthology Maps/h5_munging/h5_munging_output_files/"

h5_matrix_out_name <- paste0(vera_dir, stage_name, "_out.txt")

h5_matrix_rownames_csv <- paste0(vera_dir, stage_name, "_rownames.csv")

h5_matrix_colnames_csv <- paste0(vera_dir, stage_name, "_colnames.csv")

###

h5_matrix_in <- readMM(h5_matrix_out_name)

h5_matrix_rownames <- read.table(h5_matrix_rownames_csv,
                             header = FALSE,
                             stringsAsFactors = FALSE)$V1

h5_matrix_colnames <- read.table(h5_matrix_colnames_csv,
                             header = FALSE,
                             stringsAsFactors = FALSE)$V1

rownames(h5_matrix_in) <- h5_matrix_rownames

colnames(h5_matrix_in) <- h5_matrix_colnames
```


# Rename h5_matrix_in
```{r include=TRUE}
final_matrix_name <- h5_matrix_in
```

