---
title: "hierarchical_clustering"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(Seurat)
library(dplyr)
library(ggplot2)
library(Matrix)
library(ggcorrplot)
library(psych)
library(stringr)
library(plotly)
```

```{r include=TRUE}
test.dir <- "/home/pprakriti/princeton_google_drive/Princeton/Semesters+Classes/Fall 2017/Classes/COS 551/HW_3/gene_expression_data.csv"

gene_exp_df <- read.table(test.dir,
                      sep = ",",
                      header = TRUE,
                      stringsAsFactors = FALSE)
```

"""
  Make dendrogram.
"""
```{r include=TRUE}
# CT.ciona.mod.zeb.gsm
# neural.ciona.mod.zeb.gsm
# ciona.gsm
# mod.zeb.gsm 
your.gsm <- neural.ciona.mod.zeb.gsm
```

```{r include=TRUE}
# From one2many_orthology_map_generator.Rmd
# df 
p_cor <- cor(your.gsm, method = "spearman")
dd <- as.dist(1-p_cor)

dend <- hclust(dd, method = "average")
plot(dend, main = NULL, xlab = "", sub = "")
```
"""
  Clustergram 
"""
```{r include=TRUE}
t.your.gsm <- t(your.gsm) 
gene_mat <- as.matrix(t.your.gsm)

par(cex.main = 0.8, cexRow = 0.07)
heatmap(gene_mat, Rowv = as.dendrogram(dend))
```

```{r include=TRUE}
height <- 0.75*max(dend[[2]])

plot(dend, main = NULL, xlab = "", sub = "")
title(main = "Dendrogram + Clusters", xlab = "CTs")
cluster <- rect.hclust(dend, h=height)

ct <- cutree(dend, h=height)
```
