---
title: "notoXnoto"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(Seurat)
library(dplyr)
library(ggplot2)
library(purrr)
library(Hmisc)
library(pvclust)
library(stringr)
```

#################### PART 1: Get all unique stages and batches ####################

# Helper function to get the flags of all cells in developmental_stage_data_columns
```{r include=TRUE}

split_function <- function(x_name, split_name, split_index){
  # Returns the "flag" of a name of a cell 
  # Note: The use case is to extract the flags from colnames of
  # all_developmental_stage_data_columns (cells x genes)
  # 
  # Note: The output of strsplit is a list of length 1 with x elements, where x is the
  # number of items resulting from the split. 
  # That's why we parse the output with [[1]][1]
  #
  # Args:
  #   x_name: What is to be split. e.g. "C110.1_AAACCTGTCAGTTTGG"
  #   split_name: How you want to split x_name. e.g. "_"
  #   index: which item of the output list do you want? e.g. [1]
  #
  # Returns:
  #   split_return: The flag of the cell. e.g. "C110.1"
  
  split_return <- strsplit(x = x_name, split = split_name)[[1]][split_index]
  return(split_return)
}
```

# These are all the colnames 
```{r include=TRUE}
# get the colnames of all_developmental_stage_data_df
all_developmental_stage_data_colnames <- colnames(all_developmental_stage_data_df)
```

## Let's get the unique ones  
```{r include=TRUE}
unique_developmental_stages <- unique(sapply(all_developmental_stage_data_colnames, FUN = split_function, split_name = "_", split_index = 1))

unique_developmental_stages <- unique_developmental_stages[2:length(unique_developmental_stages)]

# "C110.1"   "C110.2"   "midG.1"   "midG.2"   "earlyN.1" "earlyN.2" "lateN.1"  "lateN.2"  "ITB.1"    "ITB.3"    "ETB.1"    "ETB.2"    "MTB.1"    "MTB.2"   
# "LTB1.1"   "LTB1.2"   "LTB2.1"   "LTB2.2"   "lv.3"     "lv.4"     "lv.1"
```

############### PART 2: Get dataframes of various timepoints and batches ###############
# 15037 genes.

# (1) C110.1/2
```{r include=TRUE}
# 2863
devt_stage_C100_df <- all_developmental_stage_data_df[ , grep("C110.1|C110.2", colnames(all_developmental_stage_data_df))]

rownames(devt_stage_C100_df) <- all_developmental_stage_data_df$GENE
```

# Test/Practice
```{r include=TRUE}
test_cells <- colnames(devt_stage_C100_df)
test_split <- strsplit(test_cells, "_")
# For each item in test_cells, split by "_", and return output in a list. Therefore, 2863 lists in test_split.
# "C110.1" "AAACCTGTCAGTTTGG"

test_split_2 <- test_split[[1]][[1]]
# "C110.1"

# Now we want to get all "test_split_2"'s for each list in test_split list.
test_sapply <- sapply(test_split, "[", 1)
# Returns a vector of "C110.1" and "C110.2"

# Now I want to make sure that all flags here have C110 and nothing else. Yes, correct!
test_detect <- str_detect(test_sapply, "C110")
sum(test_detect) == length(test_cells)


```

# (2) midG.1/2 
```{r include=TRUE}
# 3384
devt_stage_midG_df <- all_developmental_stage_data_df[ , grep("midG.1|midG.2", colnames(all_developmental_stage_data_df))]
rownames(devt_stage_midG_df) <- all_developmental_stage_data_df$GENE
```

# (3) earlyN.1/2 
```{r include=TRUE}
# 7195
devt_stage_earN_df <- all_developmental_stage_data_df[ , grep("earlyN.1|earlyN.2", colnames(all_developmental_stage_data_df))]
rownames(devt_stage_earN_df) <- all_developmental_stage_data_df$GENE
```

# (4) lateN.1/2
```{r include=TRUE}
# 8449
devt_stage_latN_df <- all_developmental_stage_data_df[ , grep("lateN.1|lateN.2", colnames(all_developmental_stage_data_df))]
rownames(devt_stage_latN_df) <- all_developmental_stage_data_df$GENE
```

# (5) ITB.1/3
```{r include=TRUE}
# 5668
devt_stage_iniT_df <- all_developmental_stage_data_df[ , grep("ITB.1|ITB.3", colnames(all_developmental_stage_data_df))]
rownames(devt_stage_iniT_df) <- all_developmental_stage_data_df$GENE
```

# (6) ETB.1/2
```{r include=TRUE}
# 7109
devt_stage_earT_df <- all_developmental_stage_data_df[ , grep("ETB.1|ETB.2", colnames(all_developmental_stage_data_df))]
rownames(devt_stage_earT_df) <- all_developmental_stage_data_df$GENE
```

# (7) MTB.1/2
```{r include=TRUE}
# 8991
devt_stage_midT_df <- all_developmental_stage_data_df[ , grep("MTB.1|MTB.2", colnames(all_developmental_stage_data_df))]
rownames(devt_stage_midT_df) <- all_developmental_stage_data_df$GENE
```

# (8) LTB1.1/2
```{r include=TRUE}
# 18535
devt_stage_ltb1_df <- all_developmental_stage_data_df[ , grep("LTB1.1|LTB1.2", colnames(all_developmental_stage_data_df))]
rownames(devt_stage_ltb1_df) <- all_developmental_stage_data_df$GENE
```

# (9) LTB2.1/2
```{r include=TRUE}
# 12635
devt_stage_ltb2_df <- all_developmental_stage_data_df[ , grep("LTB2.1|LTB2.2", colnames(all_developmental_stage_data_df))]
rownames(devt_stage_ltb2_df) <- all_developmental_stage_data_df$GENE
```

# (10) lv.1/3/4
```{r include=TRUE}
# 15791
devt_stage_lv_df <- all_developmental_stage_data_df[ , grep("lv.1|lv.3|lv.4", colnames(all_developmental_stage_data_df))]
rownames(devt_stage_lv_df) <- all_developmental_stage_data_df$GENE
```

# CHECK THAT YOU HAVE COUNTED ALL CELLS- Yes. 
```{r include=TRUE}
devt_stage_list <- list(devt_stage_C100_df, devt_stage_midG_df, devt_stage_earN_df,
                        devt_stage_latN_df, devt_stage_iniT_df, devt_stage_earT_df,
                        devt_stage_midT_df, devt_stage_ltb1_df, devt_stage_ltb2_df, devt_stage_lv_df)

# Because 1st colname is "GENE"
sum(sapply(devt_stage_list, FUN = ncol)) == ncol(all_developmental_stage_data_df)-1
```
